on:
  push:

name: run tests
jobs:

  test:
    strategy:
      matrix:
        go-version: [1.19]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -v ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Calc coverage
        run: |
          go test -covermode=count -coverprofile=count.out ./...
          go tool cover -func=count.out
      - name: Send coverage
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: count.out

